name: generate-xml-sitemap

# on:
#   workflow_run:
#     workflows: ["pages-build-deployment"]  # Name of your publishing workflow
#     types:
#       - completed

on:
  push:
    branches:
    - main
    - iPortfolio-main
    - 11ty-iPortfolio-main

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://pandyadeval.github.io/

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"